# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: ROS Style Guide C++ Format
      uses: AutoModality/action-ros-clang-format@v1.0.1
      with:
        # The name that will appear in commits when changes needs to be committed
        author-name: Format Bot
        # The email address that will appear in commits when changes needs to be committed
        author-email: formatter@github.bot
        # The commit message used when changes needs to be committed
        commit-message: Applied ROS C++ Style Guide
